/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "control_logic.v:6" *)
module control_logic(full_threshold, empty_threshold, fifo_rd, fifo_wr, clk, reset, error, almost_empty, almost_full, fifo_full, fifo_empty);
  (* src = "control_logic.v:54" *)
  wire [2:0] _000_;
  (* src = "control_logic.v:54" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  (* src = "control_logic.v:20" *)
  output almost_empty;
  (* src = "control_logic.v:21" *)
  output almost_full;
  (* src = "control_logic.v:17" *)
  input clk;
  (* src = "control_logic.v:26" *)
  wire [2:0] counter;
  (* src = "control_logic.v:14" *)
  input [2:0] empty_threshold;
  (* src = "control_logic.v:19" *)
  output error;
  (* src = "control_logic.v:23" *)
  output fifo_empty;
  (* src = "control_logic.v:22" *)
  output fifo_full;
  (* src = "control_logic.v:15" *)
  input fifo_rd;
  (* src = "control_logic.v:16" *)
  input fifo_wr;
  (* src = "control_logic.v:13" *)
  input [2:0] full_threshold;
  (* src = "control_logic.v:18" *)
  input reset;
  NOT _068_ (
    .A(counter[0]),
    .Y(_002_)
  );
  NOT _069_ (
    .A(counter[1]),
    .Y(_003_)
  );
  NOT _070_ (
    .A(counter[2]),
    .Y(_004_)
  );
  NOT _071_ (
    .A(fifo_wr),
    .Y(_005_)
  );
  NOT _072_ (
    .A(fifo_rd),
    .Y(_006_)
  );
  NOT _073_ (
    .A(reset),
    .Y(_007_)
  );
  NOT _074_ (
    .A(full_threshold[2]),
    .Y(_008_)
  );
  NOT _075_ (
    .A(empty_threshold[2]),
    .Y(_009_)
  );
  NAND _076_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_010_)
  );
  NOR _077_ (
    .A(_004_),
    .B(_010_),
    .Y(_011_)
  );
  NOT _078_ (
    .A(_011_),
    .Y(_012_)
  );
  NOR _079_ (
    .A(_007_),
    .B(_012_),
    .Y(fifo_full)
  );
  NOR _080_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_013_)
  );
  NAND _081_ (
    .A(_002_),
    .B(_003_),
    .Y(_014_)
  );
  NOR _082_ (
    .A(counter[2]),
    .B(_014_),
    .Y(_015_)
  );
  NAND _083_ (
    .A(_004_),
    .B(_013_),
    .Y(_016_)
  );
  NOR _084_ (
    .A(_007_),
    .B(_016_),
    .Y(fifo_empty)
  );
  NOR _085_ (
    .A(fifo_wr),
    .B(_006_),
    .Y(_017_)
  );
  NOT _086_ (
    .A(_017_),
    .Y(_018_)
  );
  NOR _087_ (
    .A(fifo_empty),
    .B(_018_),
    .Y(_019_)
  );
  NOR _088_ (
    .A(_005_),
    .B(fifo_rd),
    .Y(_020_)
  );
  NAND _089_ (
    .A(fifo_wr),
    .B(_006_),
    .Y(_021_)
  );
  NOR _090_ (
    .A(fifo_full),
    .B(_021_),
    .Y(_022_)
  );
  NOT _091_ (
    .A(_022_),
    .Y(_023_)
  );
  NOR _092_ (
    .A(_019_),
    .B(_022_),
    .Y(_024_)
  );
  NOR _093_ (
    .A(_002_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _094_ (
    .A(_002_),
    .B(_024_),
    .Y(_026_)
  );
  NAND _095_ (
    .A(reset),
    .B(_026_),
    .Y(_027_)
  );
  NOR _096_ (
    .A(_025_),
    .B(_027_),
    .Y(_000_[0])
  );
  NAND _097_ (
    .A(_010_),
    .B(_014_),
    .Y(_028_)
  );
  NAND _098_ (
    .A(_019_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _099_ (
    .A(counter[1]),
    .B(_018_),
    .Y(_030_)
  );
  NAND _100_ (
    .A(_029_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _101_ (
    .A(_022_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _102_ (
    .A(_011_),
    .B(_021_),
    .Y(_033_)
  );
  NAND _103_ (
    .A(_028_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _104_ (
    .A(reset),
    .B(_034_),
    .Y(_035_)
  );
  NOR _105_ (
    .A(_032_),
    .B(_035_),
    .Y(_000_[1])
  );
  NAND _106_ (
    .A(_013_),
    .B(_017_),
    .Y(_036_)
  );
  NAND _107_ (
    .A(counter[2]),
    .B(_036_),
    .Y(_037_)
  );
  NAND _108_ (
    .A(_015_),
    .B(_019_),
    .Y(_038_)
  );
  NAND _109_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _110_ (
    .A(_023_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _111_ (
    .A(_004_),
    .B(_010_),
    .Y(_041_)
  );
  NAND _112_ (
    .A(_033_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _113_ (
    .A(_040_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _114_ (
    .A(reset),
    .B(_043_),
    .Y(_044_)
  );
  NOT _115_ (
    .A(_044_),
    .Y(_000_[2])
  );
  NAND _116_ (
    .A(fifo_full),
    .B(_020_),
    .Y(_045_)
  );
  NAND _117_ (
    .A(error),
    .B(_023_),
    .Y(_046_)
  );
  NAND _118_ (
    .A(_018_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _119_ (
    .A(_007_),
    .B(_019_),
    .Y(_048_)
  );
  NAND _120_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _121_ (
    .A(_045_),
    .B(_049_),
    .Y(_001_)
  );
  NAND _122_ (
    .A(_003_),
    .B(full_threshold[1]),
    .Y(_050_)
  );
  NAND _123_ (
    .A(_002_),
    .B(full_threshold[0]),
    .Y(_051_)
  );
  NAND _124_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _125_ (
    .A(_004_),
    .B(full_threshold[2]),
    .Y(_053_)
  );
  NOR _126_ (
    .A(_003_),
    .B(full_threshold[1]),
    .Y(_054_)
  );
  NOR _127_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _128_ (
    .A(_052_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _129_ (
    .A(counter[2]),
    .B(_008_),
    .Y(_057_)
  );
  NAND _130_ (
    .A(reset),
    .B(_056_),
    .Y(_058_)
  );
  NOR _131_ (
    .A(_057_),
    .B(_058_),
    .Y(almost_full)
  );
  NOR _132_ (
    .A(_003_),
    .B(empty_threshold[1]),
    .Y(_059_)
  );
  NOR _133_ (
    .A(_002_),
    .B(empty_threshold[0]),
    .Y(_060_)
  );
  NOR _134_ (
    .A(_059_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _135_ (
    .A(_004_),
    .B(empty_threshold[2]),
    .Y(_062_)
  );
  NAND _136_ (
    .A(_003_),
    .B(empty_threshold[1]),
    .Y(_063_)
  );
  NAND _137_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _138_ (
    .A(_061_),
    .B(_064_),
    .Y(_065_)
  );
  NAND _139_ (
    .A(counter[2]),
    .B(_009_),
    .Y(_066_)
  );
  NAND _140_ (
    .A(reset),
    .B(_066_),
    .Y(_067_)
  );
  NOR _141_ (
    .A(_065_),
    .B(_067_),
    .Y(almost_empty)
  );
  (* src = "control_logic.v:54" *)
  DFF _142_ (
    .C(clk),
    .D(_001_),
    .Q(error)
  );
  (* src = "control_logic.v:54" *)
  DFF _143_ (
    .C(clk),
    .D(_000_[0]),
    .Q(counter[0])
  );
  (* src = "control_logic.v:54" *)
  DFF _144_ (
    .C(clk),
    .D(_000_[1]),
    .Q(counter[1])
  );
  (* src = "control_logic.v:54" *)
  DFF _145_ (
    .C(clk),
    .D(_000_[2]),
    .Q(counter[2])
  );
endmodule
