/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "read_logic.v:1" *)
module read_logic(fifo_rd, fifo_wr, fifo_empty, clk, reset, rd_ptr, pop);
  (* src = "read_logic.v:42" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "read_logic.v:11" *)
  input clk;
  (* src = "read_logic.v:10" *)
  input fifo_empty;
  (* src = "read_logic.v:8" *)
  input fifo_rd;
  (* src = "read_logic.v:9" *)
  input fifo_wr;
  (* src = "read_logic.v:14" *)
  output pop;
  (* src = "read_logic.v:13" *)
  output [2:0] rd_ptr;
  (* src = "read_logic.v:12" *)
  input reset;
  NOT _16_ (
    .A(fifo_empty),
    .Y(_01_)
  );
  NOT _17_ (
    .A(fifo_rd),
    .Y(_02_)
  );
  NOT _18_ (
    .A(rd_ptr[1]),
    .Y(_03_)
  );
  NOR _19_ (
    .A(_01_),
    .B(fifo_wr),
    .Y(_04_)
  );
  NOR _20_ (
    .A(_02_),
    .B(_04_),
    .Y(_05_)
  );
  NAND _21_ (
    .A(rd_ptr[0]),
    .B(_05_),
    .Y(_06_)
  );
  NAND _22_ (
    .A(reset),
    .B(_05_),
    .Y(_07_)
  );
  NOT _23_ (
    .A(_07_),
    .Y(pop)
  );
  NOR _24_ (
    .A(rd_ptr[0]),
    .B(_05_),
    .Y(_08_)
  );
  NAND _25_ (
    .A(reset),
    .B(_06_),
    .Y(_09_)
  );
  NOR _26_ (
    .A(_08_),
    .B(_09_),
    .Y(_00_[0])
  );
  NOR _27_ (
    .A(_03_),
    .B(_06_),
    .Y(_10_)
  );
  NAND _28_ (
    .A(_03_),
    .B(_06_),
    .Y(_11_)
  );
  NAND _29_ (
    .A(reset),
    .B(_11_),
    .Y(_12_)
  );
  NOR _30_ (
    .A(_10_),
    .B(_12_),
    .Y(_00_[1])
  );
  NOR _31_ (
    .A(rd_ptr[2]),
    .B(_10_),
    .Y(_13_)
  );
  NAND _32_ (
    .A(rd_ptr[2]),
    .B(_10_),
    .Y(_14_)
  );
  NAND _33_ (
    .A(reset),
    .B(_14_),
    .Y(_15_)
  );
  NOR _34_ (
    .A(_13_),
    .B(_15_),
    .Y(_00_[2])
  );
  (* src = "read_logic.v:42" *)
  DFF _35_ (
    .C(clk),
    .D(_00_[0]),
    .Q(rd_ptr[0])
  );
  (* src = "read_logic.v:42" *)
  DFF _36_ (
    .C(clk),
    .D(_00_[1]),
    .Q(rd_ptr[1])
  );
  (* src = "read_logic.v:42" *)
  DFF _37_ (
    .C(clk),
    .D(_00_[2]),
    .Q(rd_ptr[2])
  );
endmodule
