/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "arbitro2_sint.v:1" *)
module arbitro2_sint(clk, reset, data_in_arb, fifo_empty, fifos_almost_full, data_out_arb_sint, pop_sint, push_sint);
  (* src = "arbitro2_sint.v:17" *)
  wire [11:0] _00_;
  (* src = "arbitro2_sint.v:17" *)
  wire _01_;
  (* src = "arbitro2_sint.v:17" *)
  wire [3:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "arbitro2_sint.v:15" *)
  wire [1:0] \class ;
  (* src = "arbitro2_sint.v:6" *)
  input clk;
  (* src = "arbitro2_sint.v:8" *)
  input [11:0] data_in_arb;
  (* src = "arbitro2_sint.v:11" *)
  output [11:0] data_out_arb_sint;
  (* src = "arbitro2_sint.v:9" *)
  input fifo_empty;
  (* src = "arbitro2_sint.v:10" *)
  input [3:0] fifos_almost_full;
  (* src = "arbitro2_sint.v:12" *)
  output pop_sint;
  (* src = "arbitro2_sint.v:13" *)
  output [3:0] push_sint;
  (* src = "arbitro2_sint.v:7" *)
  input reset;
  NOT _24_ (
    .A(data_in_arb[11]),
    .Y(_03_)
  );
  NOT _25_ (
    .A(fifo_empty),
    .Y(_04_)
  );
  NOT _26_ (
    .A(data_in_arb[0]),
    .Y(_05_)
  );
  NOT _27_ (
    .A(data_in_arb[1]),
    .Y(_06_)
  );
  NOT _28_ (
    .A(data_in_arb[2]),
    .Y(_07_)
  );
  NOT _29_ (
    .A(data_in_arb[3]),
    .Y(_08_)
  );
  NOT _30_ (
    .A(data_in_arb[4]),
    .Y(_09_)
  );
  NOT _31_ (
    .A(data_in_arb[5]),
    .Y(_10_)
  );
  NOT _32_ (
    .A(data_in_arb[6]),
    .Y(_11_)
  );
  NOT _33_ (
    .A(data_in_arb[7]),
    .Y(_12_)
  );
  NOT _34_ (
    .A(data_in_arb[8]),
    .Y(_13_)
  );
  NOT _35_ (
    .A(data_in_arb[9]),
    .Y(_14_)
  );
  NAND _36_ (
    .A(pop_sint),
    .B(reset),
    .Y(_15_)
  );
  NOT _37_ (
    .A(_15_),
    .Y(_16_)
  );
  NAND _38_ (
    .A(data_in_arb[10]),
    .B(_16_),
    .Y(_17_)
  );
  NOT _39_ (
    .A(_17_),
    .Y(_00_[10])
  );
  NAND _40_ (
    .A(data_in_arb[11]),
    .B(_16_),
    .Y(_18_)
  );
  NOT _41_ (
    .A(_18_),
    .Y(_00_[11])
  );
  NOR _42_ (
    .A(_03_),
    .B(_17_),
    .Y(_02_[3])
  );
  NOR _43_ (
    .A(data_in_arb[10]),
    .B(_18_),
    .Y(_02_[2])
  );
  NOR _44_ (
    .A(data_in_arb[11]),
    .B(_17_),
    .Y(_02_[1])
  );
  NAND _45_ (
    .A(_03_),
    .B(_16_),
    .Y(_19_)
  );
  NOR _46_ (
    .A(data_in_arb[10]),
    .B(_19_),
    .Y(_02_[0])
  );
  NAND _47_ (
    .A(reset),
    .B(_04_),
    .Y(_20_)
  );
  NOR _48_ (
    .A(fifos_almost_full[3]),
    .B(fifos_almost_full[2]),
    .Y(_21_)
  );
  NOR _49_ (
    .A(fifos_almost_full[1]),
    .B(fifos_almost_full[0]),
    .Y(_22_)
  );
  NAND _50_ (
    .A(_21_),
    .B(_22_),
    .Y(_23_)
  );
  NOR _51_ (
    .A(_20_),
    .B(_23_),
    .Y(_01_)
  );
  NOR _52_ (
    .A(_05_),
    .B(_15_),
    .Y(_00_[0])
  );
  NOR _53_ (
    .A(_06_),
    .B(_15_),
    .Y(_00_[1])
  );
  NOR _54_ (
    .A(_07_),
    .B(_15_),
    .Y(_00_[2])
  );
  NOR _55_ (
    .A(_08_),
    .B(_15_),
    .Y(_00_[3])
  );
  NOR _56_ (
    .A(_09_),
    .B(_15_),
    .Y(_00_[4])
  );
  NOR _57_ (
    .A(_10_),
    .B(_15_),
    .Y(_00_[5])
  );
  NOR _58_ (
    .A(_11_),
    .B(_15_),
    .Y(_00_[6])
  );
  NOR _59_ (
    .A(_12_),
    .B(_15_),
    .Y(_00_[7])
  );
  NOR _60_ (
    .A(_13_),
    .B(_15_),
    .Y(_00_[8])
  );
  NOR _61_ (
    .A(_14_),
    .B(_15_),
    .Y(_00_[9])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _62_ (
    .C(clk),
    .D(_00_[0]),
    .Q(data_out_arb_sint[0])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _63_ (
    .C(clk),
    .D(_00_[1]),
    .Q(data_out_arb_sint[1])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _64_ (
    .C(clk),
    .D(_00_[2]),
    .Q(data_out_arb_sint[2])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _65_ (
    .C(clk),
    .D(_00_[3]),
    .Q(data_out_arb_sint[3])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _66_ (
    .C(clk),
    .D(_00_[4]),
    .Q(data_out_arb_sint[4])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _67_ (
    .C(clk),
    .D(_00_[5]),
    .Q(data_out_arb_sint[5])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _68_ (
    .C(clk),
    .D(_00_[6]),
    .Q(data_out_arb_sint[6])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _69_ (
    .C(clk),
    .D(_00_[7]),
    .Q(data_out_arb_sint[7])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _70_ (
    .C(clk),
    .D(_00_[8]),
    .Q(data_out_arb_sint[8])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _71_ (
    .C(clk),
    .D(_00_[9]),
    .Q(data_out_arb_sint[9])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _72_ (
    .C(clk),
    .D(_00_[10]),
    .Q(data_out_arb_sint[10])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _73_ (
    .C(clk),
    .D(_00_[11]),
    .Q(data_out_arb_sint[11])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _74_ (
    .C(clk),
    .D(_01_),
    .Q(pop_sint)
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _75_ (
    .C(clk),
    .D(_02_[0]),
    .Q(push_sint[0])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _76_ (
    .C(clk),
    .D(_02_[1]),
    .Q(push_sint[1])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _77_ (
    .C(clk),
    .D(_02_[2]),
    .Q(push_sint[2])
  );
  (* src = "arbitro2_sint.v:17" *)
  DFF _78_ (
    .C(clk),
    .D(_02_[3]),
    .Q(push_sint[3])
  );
  assign \class  = data_in_arb[11:10];
endmodule
