/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "contador_sint.v:1" *)
module contador_sint(clk, reset, req, idx, IDLE, pop, pop_0, pop_1, pop_2, pop_3, cuenta_sint, contador_4_sint, valid_sint);
  (* src = "contador_sint.v:29" *)
  wire [4:0] _000_;
  (* src = "contador_sint.v:29" *)
  wire [4:0] _001_;
  (* src = "contador_sint.v:29" *)
  wire [4:0] _002_;
  (* src = "contador_sint.v:29" *)
  wire [4:0] _003_;
  (* src = "contador_sint.v:29" *)
  wire [4:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  (* src = "contador_sint.v:12" *)
  input IDLE;
  (* src = "contador_sint.v:8" *)
  input clk;
  (* src = "contador_sint.v:19" *)
  output [4:0] contador_4_sint;
  (* src = "contador_sint.v:23" *)
  wire [4:0] counter_0;
  (* src = "contador_sint.v:24" *)
  wire [4:0] counter_1;
  (* src = "contador_sint.v:25" *)
  wire [4:0] counter_2;
  (* src = "contador_sint.v:26" *)
  wire [4:0] counter_3;
  (* src = "contador_sint.v:27" *)
  wire [4:0] counter_4;
  (* src = "contador_sint.v:18" *)
  output [4:0] cuenta_sint;
  (* src = "contador_sint.v:11" *)
  input [1:0] idx;
  (* src = "contador_sint.v:13" *)
  input pop;
  (* src = "contador_sint.v:14" *)
  input pop_0;
  (* src = "contador_sint.v:15" *)
  input pop_1;
  (* src = "contador_sint.v:16" *)
  input pop_2;
  (* src = "contador_sint.v:17" *)
  input pop_3;
  (* src = "contador_sint.v:10" *)
  input req;
  (* src = "contador_sint.v:9" *)
  input reset;
  (* src = "contador_sint.v:20" *)
  output valid_sint;
  NOT _171_ (
    .A(idx[0]),
    .Y(_143_)
  );
  NOT _172_ (
    .A(idx[1]),
    .Y(_144_)
  );
  NOT _173_ (
    .A(counter_4[0]),
    .Y(_145_)
  );
  NOT _174_ (
    .A(counter_4[1]),
    .Y(_146_)
  );
  NOT _175_ (
    .A(counter_4[2]),
    .Y(_147_)
  );
  NOT _176_ (
    .A(counter_4[3]),
    .Y(_148_)
  );
  NOT _177_ (
    .A(counter_4[4]),
    .Y(_149_)
  );
  NOT _178_ (
    .A(counter_3[0]),
    .Y(_150_)
  );
  NOT _179_ (
    .A(pop_3),
    .Y(_151_)
  );
  NOT _180_ (
    .A(counter_3[1]),
    .Y(_152_)
  );
  NOT _181_ (
    .A(counter_3[2]),
    .Y(_153_)
  );
  NOT _182_ (
    .A(counter_3[4]),
    .Y(_154_)
  );
  NOT _183_ (
    .A(counter_1[0]),
    .Y(_155_)
  );
  NOT _184_ (
    .A(pop_1),
    .Y(_156_)
  );
  NOT _185_ (
    .A(counter_1[1]),
    .Y(_157_)
  );
  NOT _186_ (
    .A(counter_1[2]),
    .Y(_158_)
  );
  NOT _187_ (
    .A(counter_1[4]),
    .Y(_159_)
  );
  NOT _188_ (
    .A(counter_2[0]),
    .Y(_160_)
  );
  NOT _189_ (
    .A(pop_2),
    .Y(_161_)
  );
  NOT _190_ (
    .A(counter_2[1]),
    .Y(_162_)
  );
  NOT _191_ (
    .A(counter_2[2]),
    .Y(_163_)
  );
  NOT _192_ (
    .A(counter_2[4]),
    .Y(_164_)
  );
  NOT _193_ (
    .A(counter_0[0]),
    .Y(_165_)
  );
  NOT _194_ (
    .A(pop_0),
    .Y(_166_)
  );
  NOT _195_ (
    .A(counter_0[1]),
    .Y(_167_)
  );
  NOT _196_ (
    .A(counter_0[2]),
    .Y(_168_)
  );
  NOT _197_ (
    .A(counter_0[4]),
    .Y(_169_)
  );
  NAND _198_ (
    .A(IDLE),
    .B(req),
    .Y(_170_)
  );
  NOT _199_ (
    .A(_170_),
    .Y(valid_sint)
  );
  NOR _200_ (
    .A(_143_),
    .B(idx[1]),
    .Y(_005_)
  );
  NAND _201_ (
    .A(counter_1[0]),
    .B(_005_),
    .Y(_006_)
  );
  NOR _202_ (
    .A(_143_),
    .B(_144_),
    .Y(_007_)
  );
  NAND _203_ (
    .A(counter_3[0]),
    .B(_007_),
    .Y(_008_)
  );
  NAND _204_ (
    .A(_006_),
    .B(_008_),
    .Y(_009_)
  );
  NOR _205_ (
    .A(idx[0]),
    .B(_144_),
    .Y(_010_)
  );
  NAND _206_ (
    .A(counter_2[0]),
    .B(_010_),
    .Y(_011_)
  );
  NOR _207_ (
    .A(idx[0]),
    .B(idx[1]),
    .Y(_012_)
  );
  NAND _208_ (
    .A(counter_0[0]),
    .B(_012_),
    .Y(_013_)
  );
  NAND _209_ (
    .A(_011_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _210_ (
    .A(_009_),
    .B(_014_),
    .Y(_015_)
  );
  NOR _211_ (
    .A(_170_),
    .B(_015_),
    .Y(cuenta_sint[0])
  );
  NAND _212_ (
    .A(counter_1[1]),
    .B(_005_),
    .Y(_016_)
  );
  NAND _213_ (
    .A(counter_3[1]),
    .B(_007_),
    .Y(_017_)
  );
  NAND _214_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NAND _215_ (
    .A(counter_2[1]),
    .B(_010_),
    .Y(_019_)
  );
  NAND _216_ (
    .A(counter_0[1]),
    .B(_012_),
    .Y(_020_)
  );
  NAND _217_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  NOR _218_ (
    .A(_018_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _219_ (
    .A(_170_),
    .B(_022_),
    .Y(cuenta_sint[1])
  );
  NAND _220_ (
    .A(counter_1[2]),
    .B(_005_),
    .Y(_023_)
  );
  NAND _221_ (
    .A(counter_3[2]),
    .B(_007_),
    .Y(_024_)
  );
  NAND _222_ (
    .A(_023_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _223_ (
    .A(counter_2[2]),
    .B(_010_),
    .Y(_026_)
  );
  NAND _224_ (
    .A(counter_0[2]),
    .B(_012_),
    .Y(_027_)
  );
  NAND _225_ (
    .A(_026_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _226_ (
    .A(_025_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _227_ (
    .A(_170_),
    .B(_029_),
    .Y(cuenta_sint[2])
  );
  NAND _228_ (
    .A(counter_1[3]),
    .B(_005_),
    .Y(_030_)
  );
  NAND _229_ (
    .A(counter_3[3]),
    .B(_007_),
    .Y(_031_)
  );
  NAND _230_ (
    .A(_030_),
    .B(_031_),
    .Y(_032_)
  );
  NAND _231_ (
    .A(counter_2[3]),
    .B(_010_),
    .Y(_033_)
  );
  NAND _232_ (
    .A(counter_0[3]),
    .B(_012_),
    .Y(_034_)
  );
  NAND _233_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _234_ (
    .A(_032_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _235_ (
    .A(_170_),
    .B(_036_),
    .Y(cuenta_sint[3])
  );
  NAND _236_ (
    .A(counter_1[4]),
    .B(_005_),
    .Y(_037_)
  );
  NAND _237_ (
    .A(counter_3[4]),
    .B(_007_),
    .Y(_038_)
  );
  NAND _238_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _239_ (
    .A(counter_2[4]),
    .B(_010_),
    .Y(_040_)
  );
  NAND _240_ (
    .A(counter_0[4]),
    .B(_012_),
    .Y(_041_)
  );
  NAND _241_ (
    .A(_040_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _242_ (
    .A(_039_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _243_ (
    .A(_170_),
    .B(_043_),
    .Y(cuenta_sint[4])
  );
  NOR _244_ (
    .A(_145_),
    .B(_170_),
    .Y(contador_4_sint[0])
  );
  NOR _245_ (
    .A(_146_),
    .B(_170_),
    .Y(contador_4_sint[1])
  );
  NOR _246_ (
    .A(_147_),
    .B(_170_),
    .Y(contador_4_sint[2])
  );
  NOR _247_ (
    .A(_148_),
    .B(_170_),
    .Y(contador_4_sint[3])
  );
  NOR _248_ (
    .A(_149_),
    .B(_170_),
    .Y(contador_4_sint[4])
  );
  NAND _249_ (
    .A(counter_4[0]),
    .B(pop),
    .Y(_044_)
  );
  NOT _250_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR _251_ (
    .A(counter_4[0]),
    .B(pop),
    .Y(_046_)
  );
  NOT _252_ (
    .A(_046_),
    .Y(_047_)
  );
  NAND _253_ (
    .A(reset),
    .B(_047_),
    .Y(_048_)
  );
  NOR _254_ (
    .A(_045_),
    .B(_048_),
    .Y(_004_[0])
  );
  NOR _255_ (
    .A(_146_),
    .B(_044_),
    .Y(_049_)
  );
  NAND _256_ (
    .A(_146_),
    .B(_044_),
    .Y(_050_)
  );
  NAND _257_ (
    .A(reset),
    .B(_050_),
    .Y(_051_)
  );
  NOR _258_ (
    .A(_049_),
    .B(_051_),
    .Y(_004_[1])
  );
  NAND _259_ (
    .A(counter_4[2]),
    .B(_049_),
    .Y(_052_)
  );
  NOT _260_ (
    .A(_052_),
    .Y(_053_)
  );
  NOR _261_ (
    .A(counter_4[2]),
    .B(_049_),
    .Y(_054_)
  );
  NAND _262_ (
    .A(reset),
    .B(_052_),
    .Y(_055_)
  );
  NOR _263_ (
    .A(_054_),
    .B(_055_),
    .Y(_004_[2])
  );
  NAND _264_ (
    .A(counter_4[3]),
    .B(_053_),
    .Y(_056_)
  );
  NOT _265_ (
    .A(_056_),
    .Y(_057_)
  );
  NAND _266_ (
    .A(_148_),
    .B(_052_),
    .Y(_058_)
  );
  NAND _267_ (
    .A(reset),
    .B(_058_),
    .Y(_059_)
  );
  NOR _268_ (
    .A(_057_),
    .B(_059_),
    .Y(_004_[3])
  );
  NOR _269_ (
    .A(_149_),
    .B(_056_),
    .Y(_060_)
  );
  NAND _270_ (
    .A(_149_),
    .B(_056_),
    .Y(_061_)
  );
  NAND _271_ (
    .A(reset),
    .B(_061_),
    .Y(_062_)
  );
  NOR _272_ (
    .A(_060_),
    .B(_062_),
    .Y(_004_[4])
  );
  NOR _273_ (
    .A(_150_),
    .B(_151_),
    .Y(_063_)
  );
  NAND _274_ (
    .A(counter_3[0]),
    .B(pop_3),
    .Y(_064_)
  );
  NOR _275_ (
    .A(counter_3[0]),
    .B(pop_3),
    .Y(_065_)
  );
  NOT _276_ (
    .A(_065_),
    .Y(_066_)
  );
  NAND _277_ (
    .A(reset),
    .B(_066_),
    .Y(_067_)
  );
  NOR _278_ (
    .A(_063_),
    .B(_067_),
    .Y(_003_[0])
  );
  NOR _279_ (
    .A(_152_),
    .B(_064_),
    .Y(_068_)
  );
  NAND _280_ (
    .A(counter_3[1]),
    .B(_063_),
    .Y(_069_)
  );
  NAND _281_ (
    .A(_152_),
    .B(_064_),
    .Y(_070_)
  );
  NAND _282_ (
    .A(reset),
    .B(_070_),
    .Y(_071_)
  );
  NOR _283_ (
    .A(_068_),
    .B(_071_),
    .Y(_003_[1])
  );
  NOR _284_ (
    .A(_153_),
    .B(_069_),
    .Y(_072_)
  );
  NAND _285_ (
    .A(_153_),
    .B(_069_),
    .Y(_073_)
  );
  NAND _286_ (
    .A(reset),
    .B(_073_),
    .Y(_074_)
  );
  NOR _287_ (
    .A(_072_),
    .B(_074_),
    .Y(_003_[2])
  );
  NAND _288_ (
    .A(counter_3[3]),
    .B(_072_),
    .Y(_075_)
  );
  NOT _289_ (
    .A(_075_),
    .Y(_076_)
  );
  NOR _290_ (
    .A(counter_3[3]),
    .B(_072_),
    .Y(_077_)
  );
  NOT _291_ (
    .A(_077_),
    .Y(_078_)
  );
  NAND _292_ (
    .A(reset),
    .B(_078_),
    .Y(_079_)
  );
  NOR _293_ (
    .A(_076_),
    .B(_079_),
    .Y(_003_[3])
  );
  NOR _294_ (
    .A(_154_),
    .B(_075_),
    .Y(_080_)
  );
  NAND _295_ (
    .A(_154_),
    .B(_075_),
    .Y(_081_)
  );
  NAND _296_ (
    .A(reset),
    .B(_081_),
    .Y(_082_)
  );
  NOR _297_ (
    .A(_080_),
    .B(_082_),
    .Y(_003_[4])
  );
  NOR _298_ (
    .A(_160_),
    .B(_161_),
    .Y(_083_)
  );
  NAND _299_ (
    .A(counter_2[0]),
    .B(pop_2),
    .Y(_084_)
  );
  NOR _300_ (
    .A(counter_2[0]),
    .B(pop_2),
    .Y(_085_)
  );
  NOT _301_ (
    .A(_085_),
    .Y(_086_)
  );
  NAND _302_ (
    .A(reset),
    .B(_086_),
    .Y(_087_)
  );
  NOR _303_ (
    .A(_083_),
    .B(_087_),
    .Y(_002_[0])
  );
  NOR _304_ (
    .A(_162_),
    .B(_084_),
    .Y(_088_)
  );
  NAND _305_ (
    .A(counter_2[1]),
    .B(_083_),
    .Y(_089_)
  );
  NAND _306_ (
    .A(_162_),
    .B(_084_),
    .Y(_090_)
  );
  NAND _307_ (
    .A(reset),
    .B(_090_),
    .Y(_091_)
  );
  NOR _308_ (
    .A(_088_),
    .B(_091_),
    .Y(_002_[1])
  );
  NOR _309_ (
    .A(_163_),
    .B(_089_),
    .Y(_092_)
  );
  NAND _310_ (
    .A(_163_),
    .B(_089_),
    .Y(_093_)
  );
  NAND _311_ (
    .A(reset),
    .B(_093_),
    .Y(_094_)
  );
  NOR _312_ (
    .A(_092_),
    .B(_094_),
    .Y(_002_[2])
  );
  NAND _313_ (
    .A(counter_2[3]),
    .B(_092_),
    .Y(_095_)
  );
  NOT _314_ (
    .A(_095_),
    .Y(_096_)
  );
  NOR _315_ (
    .A(counter_2[3]),
    .B(_092_),
    .Y(_097_)
  );
  NOT _316_ (
    .A(_097_),
    .Y(_098_)
  );
  NAND _317_ (
    .A(reset),
    .B(_098_),
    .Y(_099_)
  );
  NOR _318_ (
    .A(_096_),
    .B(_099_),
    .Y(_002_[3])
  );
  NOR _319_ (
    .A(_164_),
    .B(_095_),
    .Y(_100_)
  );
  NAND _320_ (
    .A(_164_),
    .B(_095_),
    .Y(_101_)
  );
  NAND _321_ (
    .A(reset),
    .B(_101_),
    .Y(_102_)
  );
  NOR _322_ (
    .A(_100_),
    .B(_102_),
    .Y(_002_[4])
  );
  NOR _323_ (
    .A(_155_),
    .B(_156_),
    .Y(_103_)
  );
  NAND _324_ (
    .A(counter_1[0]),
    .B(pop_1),
    .Y(_104_)
  );
  NOR _325_ (
    .A(counter_1[0]),
    .B(pop_1),
    .Y(_105_)
  );
  NOT _326_ (
    .A(_105_),
    .Y(_106_)
  );
  NAND _327_ (
    .A(reset),
    .B(_106_),
    .Y(_107_)
  );
  NOR _328_ (
    .A(_103_),
    .B(_107_),
    .Y(_001_[0])
  );
  NOR _329_ (
    .A(_157_),
    .B(_104_),
    .Y(_108_)
  );
  NAND _330_ (
    .A(counter_1[1]),
    .B(_103_),
    .Y(_109_)
  );
  NAND _331_ (
    .A(_157_),
    .B(_104_),
    .Y(_110_)
  );
  NAND _332_ (
    .A(reset),
    .B(_110_),
    .Y(_111_)
  );
  NOR _333_ (
    .A(_108_),
    .B(_111_),
    .Y(_001_[1])
  );
  NOR _334_ (
    .A(_158_),
    .B(_109_),
    .Y(_112_)
  );
  NAND _335_ (
    .A(_158_),
    .B(_109_),
    .Y(_113_)
  );
  NAND _336_ (
    .A(reset),
    .B(_113_),
    .Y(_114_)
  );
  NOR _337_ (
    .A(_112_),
    .B(_114_),
    .Y(_001_[2])
  );
  NAND _338_ (
    .A(counter_1[3]),
    .B(_112_),
    .Y(_115_)
  );
  NOT _339_ (
    .A(_115_),
    .Y(_116_)
  );
  NOR _340_ (
    .A(counter_1[3]),
    .B(_112_),
    .Y(_117_)
  );
  NOT _341_ (
    .A(_117_),
    .Y(_118_)
  );
  NAND _342_ (
    .A(reset),
    .B(_118_),
    .Y(_119_)
  );
  NOR _343_ (
    .A(_116_),
    .B(_119_),
    .Y(_001_[3])
  );
  NOR _344_ (
    .A(_159_),
    .B(_115_),
    .Y(_120_)
  );
  NAND _345_ (
    .A(_159_),
    .B(_115_),
    .Y(_121_)
  );
  NAND _346_ (
    .A(reset),
    .B(_121_),
    .Y(_122_)
  );
  NOR _347_ (
    .A(_120_),
    .B(_122_),
    .Y(_001_[4])
  );
  NOR _348_ (
    .A(_165_),
    .B(_166_),
    .Y(_123_)
  );
  NAND _349_ (
    .A(counter_0[0]),
    .B(pop_0),
    .Y(_124_)
  );
  NOR _350_ (
    .A(counter_0[0]),
    .B(pop_0),
    .Y(_125_)
  );
  NOT _351_ (
    .A(_125_),
    .Y(_126_)
  );
  NAND _352_ (
    .A(reset),
    .B(_126_),
    .Y(_127_)
  );
  NOR _353_ (
    .A(_123_),
    .B(_127_),
    .Y(_000_[0])
  );
  NOR _354_ (
    .A(_167_),
    .B(_124_),
    .Y(_128_)
  );
  NAND _355_ (
    .A(counter_0[1]),
    .B(_123_),
    .Y(_129_)
  );
  NAND _356_ (
    .A(_167_),
    .B(_124_),
    .Y(_130_)
  );
  NAND _357_ (
    .A(reset),
    .B(_130_),
    .Y(_131_)
  );
  NOR _358_ (
    .A(_128_),
    .B(_131_),
    .Y(_000_[1])
  );
  NOR _359_ (
    .A(_168_),
    .B(_129_),
    .Y(_132_)
  );
  NAND _360_ (
    .A(_168_),
    .B(_129_),
    .Y(_133_)
  );
  NAND _361_ (
    .A(reset),
    .B(_133_),
    .Y(_134_)
  );
  NOR _362_ (
    .A(_132_),
    .B(_134_),
    .Y(_000_[2])
  );
  NAND _363_ (
    .A(counter_0[3]),
    .B(_132_),
    .Y(_135_)
  );
  NOT _364_ (
    .A(_135_),
    .Y(_136_)
  );
  NOR _365_ (
    .A(counter_0[3]),
    .B(_132_),
    .Y(_137_)
  );
  NOT _366_ (
    .A(_137_),
    .Y(_138_)
  );
  NAND _367_ (
    .A(reset),
    .B(_138_),
    .Y(_139_)
  );
  NOR _368_ (
    .A(_136_),
    .B(_139_),
    .Y(_000_[3])
  );
  NOR _369_ (
    .A(_169_),
    .B(_135_),
    .Y(_140_)
  );
  NAND _370_ (
    .A(_169_),
    .B(_135_),
    .Y(_141_)
  );
  NAND _371_ (
    .A(reset),
    .B(_141_),
    .Y(_142_)
  );
  NOR _372_ (
    .A(_140_),
    .B(_142_),
    .Y(_000_[4])
  );
  (* src = "contador_sint.v:29" *)
  DFF _373_ (
    .C(clk),
    .D(_000_[0]),
    .Q(counter_0[0])
  );
  (* src = "contador_sint.v:29" *)
  DFF _374_ (
    .C(clk),
    .D(_000_[1]),
    .Q(counter_0[1])
  );
  (* src = "contador_sint.v:29" *)
  DFF _375_ (
    .C(clk),
    .D(_000_[2]),
    .Q(counter_0[2])
  );
  (* src = "contador_sint.v:29" *)
  DFF _376_ (
    .C(clk),
    .D(_000_[3]),
    .Q(counter_0[3])
  );
  (* src = "contador_sint.v:29" *)
  DFF _377_ (
    .C(clk),
    .D(_000_[4]),
    .Q(counter_0[4])
  );
  (* src = "contador_sint.v:29" *)
  DFF _378_ (
    .C(clk),
    .D(_001_[0]),
    .Q(counter_1[0])
  );
  (* src = "contador_sint.v:29" *)
  DFF _379_ (
    .C(clk),
    .D(_001_[1]),
    .Q(counter_1[1])
  );
  (* src = "contador_sint.v:29" *)
  DFF _380_ (
    .C(clk),
    .D(_001_[2]),
    .Q(counter_1[2])
  );
  (* src = "contador_sint.v:29" *)
  DFF _381_ (
    .C(clk),
    .D(_001_[3]),
    .Q(counter_1[3])
  );
  (* src = "contador_sint.v:29" *)
  DFF _382_ (
    .C(clk),
    .D(_001_[4]),
    .Q(counter_1[4])
  );
  (* src = "contador_sint.v:29" *)
  DFF _383_ (
    .C(clk),
    .D(_002_[0]),
    .Q(counter_2[0])
  );
  (* src = "contador_sint.v:29" *)
  DFF _384_ (
    .C(clk),
    .D(_002_[1]),
    .Q(counter_2[1])
  );
  (* src = "contador_sint.v:29" *)
  DFF _385_ (
    .C(clk),
    .D(_002_[2]),
    .Q(counter_2[2])
  );
  (* src = "contador_sint.v:29" *)
  DFF _386_ (
    .C(clk),
    .D(_002_[3]),
    .Q(counter_2[3])
  );
  (* src = "contador_sint.v:29" *)
  DFF _387_ (
    .C(clk),
    .D(_002_[4]),
    .Q(counter_2[4])
  );
  (* src = "contador_sint.v:29" *)
  DFF _388_ (
    .C(clk),
    .D(_003_[0]),
    .Q(counter_3[0])
  );
  (* src = "contador_sint.v:29" *)
  DFF _389_ (
    .C(clk),
    .D(_003_[1]),
    .Q(counter_3[1])
  );
  (* src = "contador_sint.v:29" *)
  DFF _390_ (
    .C(clk),
    .D(_003_[2]),
    .Q(counter_3[2])
  );
  (* src = "contador_sint.v:29" *)
  DFF _391_ (
    .C(clk),
    .D(_003_[3]),
    .Q(counter_3[3])
  );
  (* src = "contador_sint.v:29" *)
  DFF _392_ (
    .C(clk),
    .D(_003_[4]),
    .Q(counter_3[4])
  );
  (* src = "contador_sint.v:29" *)
  DFF _393_ (
    .C(clk),
    .D(_004_[0]),
    .Q(counter_4[0])
  );
  (* src = "contador_sint.v:29" *)
  DFF _394_ (
    .C(clk),
    .D(_004_[1]),
    .Q(counter_4[1])
  );
  (* src = "contador_sint.v:29" *)
  DFF _395_ (
    .C(clk),
    .D(_004_[2]),
    .Q(counter_4[2])
  );
  (* src = "contador_sint.v:29" *)
  DFF _396_ (
    .C(clk),
    .D(_004_[3]),
    .Q(counter_4[3])
  );
  (* src = "contador_sint.v:29" *)
  DFF _397_ (
    .C(clk),
    .D(_004_[4]),
    .Q(counter_4[4])
  );
endmodule
