/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "maquina_estado_sint.v:1" *)
module maquina_estado_sint(clk, reset, init, full_threshold, empty_threshold, fifos_empty, fifos_full_threshold_sint, fifos_empty_threshold_sint, idle_sint, state_sint);
  (* src = "maquina_estado_sint.v:27" *)
  wire [2:0] _000_;
  (* src = "maquina_estado_sint.v:27" *)
  wire [2:0] _001_;
  (* src = "maquina_estado_sint.v:27" *)
  wire _002_;
  (* src = "maquina_estado_sint.v:27" *)
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  (* src = "maquina_estado_sint.v:10" *)
  input clk;
  (* src = "maquina_estado_sint.v:14" *)
  input [2:0] empty_threshold;
  (* src = "maquina_estado_sint.v:15" *)
  input [8:0] fifos_empty;
  (* src = "maquina_estado_sint.v:17" *)
  output [2:0] fifos_empty_threshold_sint;
  (* src = "maquina_estado_sint.v:16" *)
  output [2:0] fifos_full_threshold_sint;
  (* src = "maquina_estado_sint.v:13" *)
  input [2:0] full_threshold;
  (* src = "maquina_estado_sint.v:18" *)
  output idle_sint;
  (* src = "maquina_estado_sint.v:12" *)
  input init;
  (* src = "maquina_estado_sint.v:11" *)
  input reset;
  (* src = "maquina_estado_sint.v:19" *)
  output [1:0] state_sint;
  NOT _060_ (
    .A(state_sint[0]),
    .Y(_004_)
  );
  NOT _061_ (
    .A(state_sint[1]),
    .Y(_005_)
  );
  NOT _062_ (
    .A(init),
    .Y(_006_)
  );
  NOT _063_ (
    .A(reset),
    .Y(_007_)
  );
  NOT _064_ (
    .A(empty_threshold[0]),
    .Y(_008_)
  );
  NOT _065_ (
    .A(empty_threshold[1]),
    .Y(_009_)
  );
  NOT _066_ (
    .A(empty_threshold[2]),
    .Y(_010_)
  );
  NOT _067_ (
    .A(full_threshold[0]),
    .Y(_011_)
  );
  NOT _068_ (
    .A(full_threshold[1]),
    .Y(_012_)
  );
  NOT _069_ (
    .A(full_threshold[2]),
    .Y(_013_)
  );
  NOT _070_ (
    .A(fifos_empty[8]),
    .Y(_014_)
  );
  NAND _071_ (
    .A(state_sint[0]),
    .B(_005_),
    .Y(_015_)
  );
  NOR _072_ (
    .A(init),
    .B(_015_),
    .Y(_016_)
  );
  NOT _073_ (
    .A(_016_),
    .Y(_017_)
  );
  NAND _074_ (
    .A(fifos_empty[0]),
    .B(fifos_empty[1]),
    .Y(_018_)
  );
  NOR _075_ (
    .A(state_sint[0]),
    .B(_006_),
    .Y(_019_)
  );
  NAND _076_ (
    .A(_004_),
    .B(init),
    .Y(_020_)
  );
  NOR _077_ (
    .A(_005_),
    .B(_019_),
    .Y(_021_)
  );
  NAND _078_ (
    .A(state_sint[1]),
    .B(_020_),
    .Y(_022_)
  );
  NAND _079_ (
    .A(fifos_empty[6]),
    .B(fifos_empty[7]),
    .Y(_023_)
  );
  NOT _080_ (
    .A(_023_),
    .Y(_024_)
  );
  NOR _081_ (
    .A(_014_),
    .B(_023_),
    .Y(_025_)
  );
  NAND _082_ (
    .A(fifos_empty[8]),
    .B(_024_),
    .Y(_026_)
  );
  NAND _083_ (
    .A(fifos_empty[2]),
    .B(fifos_empty[5]),
    .Y(_027_)
  );
  NOR _084_ (
    .A(_018_),
    .B(_027_),
    .Y(_028_)
  );
  NOT _085_ (
    .A(_028_),
    .Y(_029_)
  );
  NOR _086_ (
    .A(_026_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _087_ (
    .A(_025_),
    .B(_028_),
    .Y(_031_)
  );
  NAND _088_ (
    .A(fifos_empty[3]),
    .B(fifos_empty[4]),
    .Y(_032_)
  );
  NOT _089_ (
    .A(_032_),
    .Y(_033_)
  );
  NOR _090_ (
    .A(_022_),
    .B(_032_),
    .Y(_034_)
  );
  NAND _091_ (
    .A(_021_),
    .B(_033_),
    .Y(_035_)
  );
  NOR _092_ (
    .A(_031_),
    .B(_035_),
    .Y(_036_)
  );
  NAND _093_ (
    .A(_030_),
    .B(_034_),
    .Y(_037_)
  );
  NOR _094_ (
    .A(_016_),
    .B(_036_),
    .Y(_038_)
  );
  NAND _095_ (
    .A(_017_),
    .B(_037_),
    .Y(_039_)
  );
  NOR _096_ (
    .A(_007_),
    .B(_039_),
    .Y(_003_[0])
  );
  NOR _097_ (
    .A(_016_),
    .B(_021_),
    .Y(_040_)
  );
  NOR _098_ (
    .A(_007_),
    .B(_040_),
    .Y(_003_[1])
  );
  NOR _099_ (
    .A(_007_),
    .B(_038_),
    .Y(_002_)
  );
  NOR _100_ (
    .A(_006_),
    .B(_015_),
    .Y(_041_)
  );
  NOR _101_ (
    .A(fifos_empty_threshold_sint[0]),
    .B(_041_),
    .Y(_042_)
  );
  NAND _102_ (
    .A(_008_),
    .B(_041_),
    .Y(_043_)
  );
  NAND _103_ (
    .A(reset),
    .B(_043_),
    .Y(_044_)
  );
  NOR _104_ (
    .A(_042_),
    .B(_044_),
    .Y(_000_[0])
  );
  NOR _105_ (
    .A(fifos_empty_threshold_sint[1]),
    .B(_041_),
    .Y(_045_)
  );
  NAND _106_ (
    .A(_009_),
    .B(_041_),
    .Y(_046_)
  );
  NAND _107_ (
    .A(reset),
    .B(_046_),
    .Y(_047_)
  );
  NOR _108_ (
    .A(_045_),
    .B(_047_),
    .Y(_000_[1])
  );
  NOR _109_ (
    .A(fifos_empty_threshold_sint[2]),
    .B(_041_),
    .Y(_048_)
  );
  NAND _110_ (
    .A(_010_),
    .B(_041_),
    .Y(_049_)
  );
  NAND _111_ (
    .A(reset),
    .B(_049_),
    .Y(_050_)
  );
  NOR _112_ (
    .A(_048_),
    .B(_050_),
    .Y(_000_[2])
  );
  NOR _113_ (
    .A(fifos_full_threshold_sint[0]),
    .B(_041_),
    .Y(_051_)
  );
  NAND _114_ (
    .A(_011_),
    .B(_041_),
    .Y(_052_)
  );
  NAND _115_ (
    .A(reset),
    .B(_052_),
    .Y(_053_)
  );
  NOR _116_ (
    .A(_051_),
    .B(_053_),
    .Y(_001_[0])
  );
  NOR _117_ (
    .A(fifos_full_threshold_sint[1]),
    .B(_041_),
    .Y(_054_)
  );
  NAND _118_ (
    .A(_012_),
    .B(_041_),
    .Y(_055_)
  );
  NAND _119_ (
    .A(reset),
    .B(_055_),
    .Y(_056_)
  );
  NOR _120_ (
    .A(_054_),
    .B(_056_),
    .Y(_001_[1])
  );
  NOR _121_ (
    .A(fifos_full_threshold_sint[2]),
    .B(_041_),
    .Y(_057_)
  );
  NAND _122_ (
    .A(_013_),
    .B(_041_),
    .Y(_058_)
  );
  NAND _123_ (
    .A(reset),
    .B(_058_),
    .Y(_059_)
  );
  NOR _124_ (
    .A(_057_),
    .B(_059_),
    .Y(_001_[2])
  );
  (* src = "maquina_estado_sint.v:27" *)
  DFF _125_ (
    .C(clk),
    .D(_001_[0]),
    .Q(fifos_full_threshold_sint[0])
  );
  (* src = "maquina_estado_sint.v:27" *)
  DFF _126_ (
    .C(clk),
    .D(_001_[1]),
    .Q(fifos_full_threshold_sint[1])
  );
  (* src = "maquina_estado_sint.v:27" *)
  DFF _127_ (
    .C(clk),
    .D(_001_[2]),
    .Q(fifos_full_threshold_sint[2])
  );
  (* src = "maquina_estado_sint.v:27" *)
  DFF _128_ (
    .C(clk),
    .D(_000_[0]),
    .Q(fifos_empty_threshold_sint[0])
  );
  (* src = "maquina_estado_sint.v:27" *)
  DFF _129_ (
    .C(clk),
    .D(_000_[1]),
    .Q(fifos_empty_threshold_sint[1])
  );
  (* src = "maquina_estado_sint.v:27" *)
  DFF _130_ (
    .C(clk),
    .D(_000_[2]),
    .Q(fifos_empty_threshold_sint[2])
  );
  (* src = "maquina_estado_sint.v:27" *)
  DFF _131_ (
    .C(clk),
    .D(_002_),
    .Q(idle_sint)
  );
  (* src = "maquina_estado_sint.v:27" *)
  DFF _132_ (
    .C(clk),
    .D(_003_[0]),
    .Q(state_sint[0])
  );
  (* src = "maquina_estado_sint.v:27" *)
  DFF _133_ (
    .C(clk),
    .D(_003_[1]),
    .Q(state_sint[1])
  );
endmodule
