/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "write_logic.v:1" *)
module write_logic(fifo_wr, fifo_rd, fifo_full, clk, reset, wr_ptr, push);
  (* src = "write_logic.v:41" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "write_logic.v:12" *)
  input clk;
  (* src = "write_logic.v:11" *)
  input fifo_full;
  (* src = "write_logic.v:10" *)
  input fifo_rd;
  (* src = "write_logic.v:9" *)
  input fifo_wr;
  (* src = "write_logic.v:15" *)
  output push;
  (* src = "write_logic.v:13" *)
  input reset;
  (* src = "write_logic.v:14" *)
  output [2:0] wr_ptr;
  NOT _13_ (
    .A(wr_ptr[2]),
    .Y(_01_)
  );
  NOT _14_ (
    .A(fifo_rd),
    .Y(_02_)
  );
  NOT _15_ (
    .A(reset),
    .Y(_03_)
  );
  NOT _16_ (
    .A(wr_ptr[0]),
    .Y(_04_)
  );
  NAND _17_ (
    .A(fifo_full),
    .B(_02_),
    .Y(_05_)
  );
  NAND _18_ (
    .A(fifo_wr),
    .B(_05_),
    .Y(_06_)
  );
  NOR _19_ (
    .A(_04_),
    .B(_06_),
    .Y(_07_)
  );
  NAND _20_ (
    .A(_04_),
    .B(_06_),
    .Y(_08_)
  );
  NAND _21_ (
    .A(reset),
    .B(_08_),
    .Y(_09_)
  );
  NOR _22_ (
    .A(_07_),
    .B(_09_),
    .Y(_00_[0])
  );
  NOR _23_ (
    .A(wr_ptr[1]),
    .B(_07_),
    .Y(_10_)
  );
  NAND _24_ (
    .A(wr_ptr[1]),
    .B(_07_),
    .Y(_11_)
  );
  NAND _25_ (
    .A(reset),
    .B(_11_),
    .Y(_12_)
  );
  NOR _26_ (
    .A(_10_),
    .B(_12_),
    .Y(_00_[1])
  );
  NOR _27_ (
    .A(_01_),
    .B(_12_),
    .Y(_00_[2])
  );
  NOR _28_ (
    .A(_03_),
    .B(_06_),
    .Y(push)
  );
  (* src = "write_logic.v:41" *)
  DFF _29_ (
    .C(clk),
    .D(_00_[0]),
    .Q(wr_ptr[0])
  );
  (* src = "write_logic.v:41" *)
  DFF _30_ (
    .C(clk),
    .D(_00_[1]),
    .Q(wr_ptr[1])
  );
  (* src = "write_logic.v:41" *)
  DFF _31_ (
    .C(clk),
    .D(_00_[2]),
    .Q(wr_ptr[2])
  );
endmodule
